# Generated by Django 5.2.16 on 2026-07-24 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_show_on_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSignupColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('key', models.SlugField(editable=False, max_length=48)),
                ('sort_order', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_columns', to='events.event')),
            ],
            options={
                'ordering': ['sort_order', 'created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EventSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulgo', models.CharField(max_length=80)),
                ('normalized_vulgo', models.CharField(editable=False, max_length=80)),
                ('attending', models.BooleanField()),
                ('values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='events.event')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('event', 'normalized_vulgo'), name='unique_event_signup_vulgo')],
            },
        ),
    ]
