# Generated by Codex on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_eventsignupcolumn_eventsignup"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="signup_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="eventsignupcolumn",
            name="field_options",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="eventsignupcolumn",
            name="field_type",
            field=models.CharField(
                choices=[("text", "Text"), ("textarea", "Textarea"), ("select", "Select"), ("checkbox", "Checkbox")],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="eventsignupcolumn",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventsignupcolumn",
            name="is_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventsignupcolumn",
            name="placeholder",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
