# Generated by Django 5.2.16 on 2026-08-04 15:07

import uuid

import django.utils.timezone
from django.db import migrations, models


def backfill_calendar_uids(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    for event in Event.objects.filter(calendar_uid__isnull=True):
        event.calendar_uid = f"event-{uuid.uuid4()}@avfroburger.ch"
        event.save(update_fields=["calendar_uid"])


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_public_signup_contract"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCalendarTombstone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("calendar_uid", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("was_public", models.BooleanField(default=False)),
                ("calendar_sequence", models.PositiveIntegerField(default=0)),
                ("cancelled_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-cancelled_at", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="calendar_sequence",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="event",
            name="calendar_uid",
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="event",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_calendar_uids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="event",
            name="calendar_uid",
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
