# Generated by Django 5.2.16 on 2026-08-11 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventcalendartombstone_event_calendar_sequence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_id', models.PositiveBigIntegerField(db_index=True)),
                ('action', models.CharField(choices=[('created', 'Erstellt'), ('updated', 'Aktualisiert'), ('hidden', 'Verborgen'), ('shown', 'Sichtbar gemacht'), ('deleted', 'Gelöscht'), ('restored', 'Wiederhergestellt'), ('purged', 'Endgültig gelöscht')], max_length=16)),
                ('source', models.CharField(choices=[('public_form', 'Web-Formular'), ('internal', 'Intern'), ('api', 'API')], max_length=16)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='eventsignup',
            name='unique_event_signup_vulgo',
        ),
        migrations.AddField(
            model_name='eventsignup',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='eventsignup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsignup',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventsignup',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Steuert, ob dieser Eintrag auf der öffentlichen Anlassseite erscheint.', verbose_name='Öffentlich sichtbar'),
        ),
        migrations.AddConstraint(
            model_name='eventsignup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('event', 'normalized_vulgo'), name='unique_event_signup_vulgo'),
        ),
        migrations.AddField(
            model_name='signupauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signupauditlog',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_audit_logs', to='events.event'),
        ),
    ]
