# Generated by Django 5.2.16 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_signupauditlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="signup_deadline_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
