# Generated by Django 5.2.16 on 2026-09-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_signup_deadline_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsignup',
            name='pin_failed_attempts',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='eventsignup',
            name='pin_hash',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
        migrations.AddField(
            model_name='eventsignup',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
