# Generated by Django 5.2.16 on 2026-09-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventsignup_pin_failed_attempts_eventsignup_pin_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_timing',
            field=models.CharField(blank=True, choices=[('', 'Ohne Zusatz'), ('st', 's.t.'), ('ct', 'c.t.')], default='', max_length=2, verbose_name='Zeitangabe'),
        ),
    ]
